### PR TITLE
Added the meetup card for the Weekly Dev Chat.

### PR DESCRIPTION
**Pull request by EmmettAMartin**
Added the Weekly Dev Chat to the meetups section of the DevEdmonton Page.

### CODE REVIEW

**Comment by MandyMeindersma** [comment]
Netlify is being so weird. It wants me to approve it before it generates a preview but I want to see a preview before deploying. So the code looks good, I'll approve, but don't merge until I give another okay after checking the deploy.

**Comment by MandyMeindersma** [comment]
Thank you for adding this!

**Review by MandyMeindersma — APPROVED** [review]

**Comment by MandyMeindersma** [comment]
hmmm netlify is still being weird, give me some time to look into it

**Comment by MarkBennett** [comment]
@MandyMeindersma if you sign in to Netlify and go to the deploy previews page:

https://app.netlify.com/sites/dev-edmonton/deploys

You can see this message there...

Screenshot 2023-04-10 at 10 14 56 AM

It looks like Netlify isn't allowing unapproved builds access to "sensitive" variables which have our credentials in them. This is probably a good idea, but might be overkill for the devedmonton.com site. It looks like you can change the setting here:

https://app.netlify.com/sites/dev-edmonton/settings/env#site-policies

Hope this helps sort out the issue!

**Comment by MandyMeindersma** [comment]
ohhhhhhh so when I was logging in I was only seeing:

image


Cause I was logging in with the wrong account 😬  my bad, thank you for saving the day Mark

**Comment by MandyMeindersma** [comment]
@EmmettAMartin Okay so the deploy failed which just means you have to fix a couple things. 

It failed just because we are picky about line breaks and other linting things :)

Here is a screen shot from the broken build: 
image


You should be able to see this if you click around with the netlify stuff though too. 

In our readme though it shows how to run the linter: `npm run lint-check`. 

I know you were having issues with npm but hopefully you can run that? and it should give you the same errors as netlify does. Just fix those line breaks and then we can merge it in!

**Comment by EmmettAMartin** [comment]
> @EmmettAMartin Okay so the deploy failed which just means you have to fix a couple things.
> 
> It failed just because we are picky about line breaks and other linting things :)
> 
> Here is a screen shot from the broken build: image
> 
> You should be able to see this if you click around with the netlify stuff though too.
> 
> In our readme though it shows how to run the linter: `npm run lint-check`.
> 
> I know you were having issues with npm but hopefully you can run that? and it should give you the same errors as netlify does. Just fix those line breaks and then we can merge it in!

Just fixed them now!

**Comment by MandyMeindersma** [comment]
@all-contributors please add @EmmettAMartin  for code

**Comment by MandyMeindersma** [comment]
and it's live! https://devedmonton.com/

**Comment by mrbiggred** [comment]
Thanks @EmmettAMartin, @MarkBennett, and @MandyMeindersma for adding the Weekly Dev Chat to the Dev Edmonton website.  It is much appreciated.

**Pull request merged**
