### PR TITLE
Issue 43 mailing list

### PR DESCRIPTION
**Pull request by DerrykBoyd**
Adds a newsletter signup form to the home page #43 

Currently setup to use a netlify function, which will ping the mailchimp API and add a contact to the mailchimp account. It's linked to a test account I setup, but can be quickly switched to a DES account by changing the environment variables in netlify.

Creating a draft PR so we can test the form on the deploy preview.

### CODE REVIEW

**Comment by dboydgit** [comment]
@MarkBennett I've set this up to connect to a test mailchimp account for now, should be trivial to switch out to a different service now that the netlify function is setup. 

In the mean time, can you review the copy / design / functionality and suggest any changes there while we wait for the mailing service to be finaliased?

**Comment by MarkBennett** [comment]
> In the mean time, can you review the copy / design / functionality and suggest any changes there while we wait for the mailing service to be finaliased?

Taking a look at the copy / layout now. I'll leave a review with comments.

**Comment by MarkBennett** [comment]
> I've set this up to connect to a test mailchimp account for now, should be trivial to switch out to a different service now that the netlify function is setup.

Nice work! Celina is looking into MailChimp and other mailing list options and should have a recommendation on what to set up shortly.

**Comment by MarkBennett** [comment]
Just took a quick look. I didn't realized the PR is in draft so I can't actually submit a review.

Overall I like it, along with the look you're going for. I'm not totally sure that the amount of space we're giving it at the top of the page there is right for the number of people that might be using it yet. We're doing a community survey here and should have a better sense of how important the mailing list is vs the other communication platforms we've got.

Do you think you could bump it down to the bottom of the page between the grey footer and the "Get Involved" section?

I'm thinking once we know where people would like to follow / subscribe to us from we can rework that flow on the page to make all our socials and communication channels clearer.

**Comment by dboydgit** [comment]
OK, I've moved the component down to just above the footer. Just waiting on the final word for the mailing list to use.

**Comment by NonMint** [comment]
@DerrykBoyd, on Wednesday we decided on Mailchimp, and I've signed up for a DES mailchimp account. I have some 1Password credentials to share with you, or we can meet up to generate an API key or something. What else can I do to help support this initiative?

**Comment by DerrykBoyd** [comment]
@NonMint Do you have access to the Netlify account? Probably the easiest thing is for you to go into the Netlify build settings and switch out the two Mailchimp environment variables.

https://app.netlify.com/sites/dev-edmonton/settings/deploys#environment

I do have a DES 1password account, but I can't remember which computer I signed up on, so need some time to log back in. I'll figure that out this weekend and if you need to share the Mailchimp login for me to grab the API key I can.

**Comment by MandyMeindersma** [comment]
@NonMint the netlify account password is saved in 1password so you do have access

**Comment by NonMint** [comment]
I don't think that password has been shared with me @MandyMeindersma ?

**Comment by MandyMeindersma** [comment]
now you have it 😂  sorry

**Comment by NonMint** [comment]
Updated the environment information. I set up an email address (mailchimp@devedmonton.com) and a MailChimp account using that email. Anything else needed? Or can we test this sucker out.

**Comment by DerrykBoyd** [comment]
I've resolved some conflicts and brought this branch up to date. That's triggered a new build so should be testable at https://deploy-preview-72--dev-edmonton.netlify.app/ now @NonMint

**Comment by NonMint** [comment]
Getting a 403 on both Chrome and Firefox when I try and enter my email.

image

**Comment by DerrykBoyd** [comment]
@NonMint a few things to check. What does the start of the url show when you login to mailchimp? Might need to switch that as well, my test account was `us1`

image

Also just to confirm the `list_ID`, it looks right, but did you get it from `Audience > All contacts > Settings > Audience name and defaults` in the mailchimp UI, it should look like this

image

**Comment by DerrykBoyd** [comment]
@NonMint did you get a chance to check these?

**Comment by MandyMeindersma** [comment]
@NonMint Did you save the password for mailchimp in 1password anywhere? I am trying to find where to log in to test the stuff for derryk but I can't find any password.

**Comment by MandyMeindersma** [comment]
image
image

**Comment by MandyMeindersma** [comment]
maybe those shouldn't be public 😂  but the id looks right on netlify. You want to change the server name @DerrykBoyd ?

**Comment by MandyMeindersma** [comment]
image
looks like it is working to me!

**Review by MandyMeindersma — APPROVED** [review]

**Comment by DerrykBoyd** [comment]
> looks like it is working to me!

Excellent, thank's for updating that @MandyMeindersma

**Comment by MandyMeindersma** [comment]
Looks good to me. I'll import the google contacts to the mailchimp list later. I made a ticket on our ticket tracker so I don't forget
image

**Pull request merged**
