### PR TITLE
remove Go Meetup

### PR DESCRIPTION
**Pull request by nathany**
Note: the dev server was being really flaky (constant redirects) when I made this change, but the production build looked fine. I don't have `nvm` so it may have been related to that. Might want to double check the tooling.

### CODE REVIEW

**Comment by MandyMeindersma** [comment]
didn't see anything weird in the preview!

**Review by MandyMeindersma — APPROVED** [review]

**Comment by nathany** [comment]
thanks Mandy!

**Comment by MarkBennett** [comment]
Are you winding down the Go meetup @nathany?

**Comment by nathany** [comment]
@MarkBennett  Thanks for asking! 

Yeah. It's been winding down for a while. I haven't been using Go for a few years, so my interest in coming up with presentations is lacking, and interest in the meetup was dwindling anyway.

Maybe I'll help with another meetup post-pandemic, or maybe I'll just be an attendee. Not sure yet.

Hope you are doing well.

**Comment by MarkBennett** [comment]
> @MarkBennett Thanks for asking!
> 
> Yeah. It's been winding down for a while. I haven't been using Go for a few years, so my interest in coming up with presentations is lacking, and interest in the meetup was dwindling anyway.
> 
> Maybe I'll help with another meetup post-pandemic, or maybe I'll just be an attendee. Not sure yet.
> 
> Hope you are doing well.

I totally understand @nathany. Meetups have really changed since COVID. Hoping oneday we'll be back to normal, but until then it's hard.

You've done so much to keep this meetup running, and to support the community in general. Always nice to see you, regardless of if you're running the show. Take care and hopefully see you again soon. 😄

**Pull request merged**
