### PR TITLE
Add R user group to Meetups section

### PR DESCRIPTION
**Pull request by psolymos**
Hey @MarkBennett, as per your suggestion on Slack, I added an R logo (svg) and a card plus associate data to the Meetups section for the Edmonton R User Group.

`npm run dev` run with usual warnings about upcoming changes, client/server compiled successfully, rendering looked all right.

### CODE REVIEW

**Comment by MandyMeindersma** [comment]
@psolymos If you fix your build errors someone will take a look!

**Review by MandyMeindersma — APPROVED** [review]

**Comment by MandyMeindersma** [comment]
I might still wait for @MarkBennett 's approval but looks good!

**Comment by MarkBennett** [comment]
> I might still wait for @MarkBennett 's approval but looks good!

Eek! Sorry. Totally promised to look at this and then forgot! 😛

**Review by MarkBennett — APPROVED** [review]
Ship it! ⛴️

**Comment by psolymos** [comment]
Thanks a lot for taking a look!

**Pull request merged**
