### PR TITLE
Add images

### PR DESCRIPTION
**Pull request by MarkBennett**
Update the images. They still need a pass to optimize for size and quality as it's yikes on mobile.

### CODE REVIEW

**Comment by MarkBennett** [comment]
Ugh, there's a bunch of conflicts on this branch now. Will update in the AM.

**Review by dboydgit — COMMENTED** [review]
Looks good.

**Comment by dboydgit** [comment]
I think I got all the conflict sorted out now :+1:

**Comment by MarkBennett** [comment]
Nice work on cleaning this up and merging. Thanks for all your work on this @dboydgit! :)

**Comment by dboydgit** [comment]
No problem! I'm not sure what was happening with those conflicts, they were
odd. Some content getting duplicated for some reason.

**Pull request merged**
