### PR TITLE
Update links to Slack invite

### LINKED ISSUE #146: Drop the Slack inviter app and just use an invite link
At some point since the website launched Slack has added the ability to create invite links that don't expire.

Given that Heroku is going to charge soon, and that we can now create a permanent invite link, I propose that we:

1. Delete the Heroku inviter app
2. Update the "Join our Slack" link to use a permanent invite link instead.

You can [read about how to create a permanent link in the Slack docs](https://slack.com/help/articles/201330256-Invite-new-members-to-your-workspace#:~:text=Desktop%20iOS%20Android-,Select%20Invite%20people%20to%20%5Bworkspace%20name%5D%20from%20the%20menu.,when%20someone%20uses%20your%20link.), but I created one that's ready to go if anyone wants to take this on. I can do a PR after work if there's interest:

https://join.slack.com/t/devedmonton/shared_invite/zt-1h0s5j0g4-ntARRvWGapJcnckM34jdZw

### PR DESCRIPTION
**Pull request by MarkBennett**
## Changes
* MAJOR: Drop the link to the old Slack inviter app on Heroku and use a link to the official Slack join app instead

## See Also
Closes #146

### CODE REVIEW

**Comment by MandyMeindersma** [comment]
I am still scared this will only work for 100 people though. And it won't notify us after 100 people have used it?

**Comment by MarkBennett** [comment]
Just found this in the docs. Looks like you're right @MandyMeindersma! [It's limited to 400 people according to this page in the docs](https://slack.com/help/articles/201330256-Invite-new-members-to-your-workspace#:~:text=On%20the%20free%2C%20Pro%2C%20and%20Business%2B%20plans%2C%20members%20with%20permission%20to%20send%20invitations%20can%20also%20share%20an%20invite%20link.%20Each%20invite%20link%20can%20be%20used%20by%20up%20to%20400%20people.).

This reddit thread says that you can ask Slack support to generate a link that lasts for more people...

https://www.reddit.com/r/Slack/comments/xc88dw/invite_link_that_doesnt_expire/

Maybe we try that?

**Comment by MandyMeindersma** [comment]
Message to slack support sent! I'll let you know what they say.

**Comment by MandyMeindersma** [comment]
Okay so I chatted with slack and we have a link but there are some limitations. 

It expires in a year (that means easy hacktoberfest pr for someone lol) and it only holds 2000 people. I will set a reminder for myself to get a new link next year. They also do not give notifications if we are getting close to the 2000 so that means I will just have to monitor the number of people in the slack. We currently have 3785 in the announcements channel so when we get close to 5500 I'll ask for another one but I can't imagine we will get more than 2000 people in a year. 

The one change I would like to see in the pr though cause:
image


Can we just add like a bold or red sentance about if you get a "invalid link" error to email "board@decedmonton.com"

**Comment by MandyMeindersma** [comment]
https://github.com/devedmonton/devedmonton.com/issues/148

**Comment by MandyMeindersma** [comment]
Oh I forgot to give you the link lol https://join.slack.com/t/devedmonton/shared_invite/zt-1hqylgb8i-pKr5nUmRwOJwdLHVce0rXg

**Comment by MarkBennett** [comment]
> Can we just add like a bold or red sentance about if you get a "invalid link" error to email "[board@decedmonton.com](mailto:board@decedmonton.com)"

Thanks for getting this link @MandyMeindersma. I can update the PR and add the warning you mentioned.

Annoying that they won't just make it work forever.

Also, do you know if setting up this link has something to do with the "free trial" our Slack is suddenly on? If so, is there any issues with this not working when the trial ends?

**Comment by MandyMeindersma** [comment]
I was emailing with the before the free trial so I don't think it will be affected :)

**Comment by MarkBennett** [comment]
I've just pushed the updated link and a message about what to do if it errors out, along with a template in email in the link body.

Screen Shot 2022-10-12 at 12 47 45 PM

Ready for a fresh review @MandyMeindersma!

**Review by MandyMeindersma — APPROVED** [review]

**Pull request merged**
