### PR TITLE
Use a tiny "DES" icon instead of the "<D>"

### PR DESCRIPTION
**Pull request by MarkBennett**
This is more consistent with what we've got in other places like Twitter and Github.

### CODE REVIEW

**Comment by dboydgit** [comment]
I found out yesterday that the favicon.ico has to be exactly 32x32px or nuxt wont grab it in the build. Is that the size you used @MarkBennett ?

**Comment by MarkBennett** [comment]
> I found out yesterday that the favicon.ico has to be exactly 32x32px or nuxt wont grab it in the build. Is that the size you used @MarkBennett ?

I ran the image through a favicon generator so I'm assuming so but let me go to my computer and check the file there..

**Comment by MarkBennett** [comment]
Just checked and it's 42x42. Will that work for Nuxt @dboydgit?

Screenshot from 2020-10-23 12-28-15

**Comment by MarkBennett** [comment]
Just checked and it's showing up on the preview deploy on netlify, so I'm thinking it should work.

Screenshot from 2020-10-23 12-40-12

https://deploy-preview-41--dev-edmonton.netlify.app/

**Comment by dboydgit** [comment]
I merged it, we can come back to it if it doesn't work.

**Comment by MarkBennett** [comment]
@allcontributors add @MarkBennett as code, design, review, documentation

**Pull request merged**
