### PR TITLE
Initial commit for STUDENT resources

### PR DESCRIPTION
**Pull request by djphan**
https://github.com/devedmonton/devedmonton.com/issues/75

First pass of student resources done on a separate page. Thoughts? Feedback? 

Screen Shot 2021-10-31 at 11 16 56 PM

### CODE REVIEW

**Comment by MandyMeindersma** [comment]
I like the idea of having a seperate section for student specifically. 

I think with @dboydgit pr: #128 he will add resources to the main menu and then student resources can just go below? thoughts?

Then you can remove your menu add

We will wait for @dboydgit to be merged before merging this (as his makes a couple helpful changes to the meetup cards

**Comment by NonMint** [comment]
Do we want to have a list of free resources as well? There is plenty of great documentation out there, and we can provide a pretty long list of awesome stuff. Or just utilizing some other list that someone has collated, like https://github.com/ripienaar/free-for-dev#table-of-contents?

**Comment by djphan** [comment]
@MandyMeindersma @DerrykBoyd Did we want to leverage the new resources block that got added or is that starting to make a the page too long? I can keep this page tough or make it another section in the main page.

@NonMint I can add more resources but this was a starting point :)

**Comment by DerrykBoyd** [comment]
> @MandyMeindersma @DerrykBoyd Did we want to leverage the new resources block that got added or is that starting to make a the page too long? I can keep this page tough or make it another section in the main page.
> 
> @NonMint I can add more resources but this was a starting point :)

Yeah I think a new Page for resources would be fine. Can just move the block on the home page into the new page.

**Comment by MandyMeindersma** [comment]
I am gonna close this finally Dan :P You can re open if you want or wait until next hacktoberfest lol

**Pull request closed without merging**
