### PR TITLE
Update packages & fix linting errors

### PR DESCRIPTION
**Pull request by EmmettAMartin**
While trying to run this website I ran into the error below:
```
ERROR in ./.nuxt/components/nuxt-error.vue
Module build failed (from ./node_modules/@nuxt/components/dist/loader.js):
Error: 

Vue packages version mismatch:

- vue@2.6.12
- vue-template-compiler@2.5.22
```
I fixed it by running `npm update`.
I also fixed some linting errors while running `npm build`:
```
$ npm run build

> devedmonton@1.0.0 build
> npm run test && nuxt build


> devedmonton@1.0.0 test
> npm run lint-check


> devedmonton@1.0.0 lint-check
> eslint '{components,layouts,pages}/**/*.vue'


/workspace/devedmonton.com/components/BoardMember.vue
  78:25  warning  'v-html' directive can lead to XSS attack  vue/no-v-html

/workspace/devedmonton.com/components/EventsSection.vue
  53:24  error  Delete `⏎···················`  prettier/prettier

/workspace/devedmonton.com/components/MeetupsSection.vue
  147:28  error  Delete `⏎·······················`  prettier/prettier

✖ 3 problems (2 errors, 1 warning)
  2 errors and 0 warnings potentially fixable with the `--fix` option.
```

Let me know what you think. My main goal is to add the [Weekly Dev Chat](https://weeklydevchat.com/) in another PR.
I'm working with Chris C (@mrbiggred).

### CODE REVIEW

**Comment by MandyMeindersma** [comment]
Looks good to me! Thank you for making these updates

**Review by MandyMeindersma — APPROVED** [review]

**Review by MandyMeindersma — CHANGES_REQUESTED** [review]
Actually I lied, something seems to be going wrong with the deploy with netlify. If you click "deploy Preview ready!" you will see what I mean

**Comment by EmmettAMartin** [comment]
> Actually I lied, something seems to be going wrong with the deploy with netlify. If you click "deploy Preview ready!" you will see what I mean

Can you tell me where would I find this?

**Comment by mrbiggred** [comment]
@EmmettAMartin you can find the deploy preview under the checks.  You might have to be logged in to GitHub to see it.  The preview is missing the CSS.  Similar to the problem we first had when trying to setup the development environment.

Since the site looks fine when we run `npm run` I assume the problem is with the `npm build` or `npm generate`.  I'm not familiar with Vue/Node but I assume those commands will pre-compile the CSS, Javascript, etc.  My current guess is there is an issue pre-compiling the CSS so the styles are not found in production.

Another possibility is upgrading the NPM packages broke something.

Finally both my guess could be wrong.  I've never worked on a Vue/Node website before.

image

**Comment by EmmettAMartin** [comment]
> @EmmettAMartin you can find the deploy preview under the checks. You might have to be logged in to GitHub to see it. The preview is missing the CSS. Similar to the problem we first had when trying to setup the development environment.
> 
> Since the site looks fine when we run `npm run` I assume the problem is with the `npm build` or `npm generate`. I'm not familiar with Vue/Node but I assume those commands will pre-compile the CSS, Javascript, etc. My current guess is there is an issue pre-compiling the CSS so the styles are not found in production.
> 
> Another possibility is upgrading the NPM packages broke something.
> 
> Finally both my guess could be wrong. I've never worked on a Vue/Node website before.
> 
> image

Thank you!

**Comment by EmmettAMartin** [comment]
@MandyMeindersma We are going to close the PR because we were using node 18, instead of node 18. It is the reason we got the errors when we first tried to run it and thought we had to run `npm update`.

Now that we have the correct node version in our development the website runs just fine.  We will create another PR with a link to the Weekly Dev Chat website.

P.S. - Now that we are running on node 16, we attempted to run `npm update` but it also caused issues.  We are not smart enough to know how to fix these errors.  At least not at this time.  We will leave updating the npm packages to those who have more javascript experience.

```
$ npm run dev

> devedmonton@1.0.0 dev
> nuxt

ℹ Using Tailwind CSS from ~/assets/css/tailwind.css                                                                                                                           nuxt:tailwindcss 22:14:24
ℹ Merging Tailwind config from ~/tailwind.config.js                                                                                                                           nuxt:tailwindcss 22:14:24

   ╭───────────────────────────────────────╮
   │                                       │
   │   Nuxt @ v2.16.3                      │
   │                                       │
   │   ▸ Environment: development          │
   │   ▸ Rendering:   server-side          │
   │   ▸ Target:      server               │
   │                                       │
   │   Listening: http://localhost:3000/   │
   │                                       │
   ╰───────────────────────────────────────╯

ℹ Preparing project for development                                                                                                                                                            22:14:25
ℹ Initial build may take a while                                                                                                                                                               22:14:25

 FATAL  Cannot set properties of undefined (setting 'stage')                                                                                                                                   22:14:25

  at node_modules/@nuxtjs/tailwindcss/lib/module.js:56:26
  at node_modules/hable/dist/hable.js:1:990
  at node_modules/hable/dist/hable.js:1:208
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Nuxt.callHook (node_modules/hable/dist/hable.js:1:959)
  at async Builder.build (node_modules/@nuxt/builder/dist/builder.js:232:5)
  at async Object._buildDev (node_modules/@nuxt/cli/dist/cli-dev.js:79:5)
  at async Object.startDev (node_modules/@nuxt/cli/dist/cli-dev.js:55:7)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-dev.js:44:5)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:356:7)


   ╭─────────────────────────────────────────────────────────────────────╮
   │                                                                     │
   │   ✖ Nuxt Fatal Error                                                │
   │                                                                     │
   │   TypeError: Cannot set properties of undefined (setting 'stage')   │
   │                                                                     │
   ╰─────────────────────────────────────────────────────────────────────╯

```

**Pull request closed without merging**
