### PR TITLE
Add `package-lock.json`

### PR DESCRIPTION
**Pull request by MarkBennett**
I usually check this in so we're all on the same version of packages.

### CODE REVIEW

**Comment by MarkBennett** [comment]
Thoughts @ dboydgit @stormwarning?

**Review by stormwarning — APPROVED** [review]
Absolutely 👍

**Comment by stormwarning** [comment]
Isn't this already in the repo though?

**Comment by MarkBennett** [comment]
> Isn't this already in the repo though?

You're right @stormwarning. I think this was just me being bad at `git`. Closing.

**Pull request closed without merging**
